#name: .NET Tests
#
#on:
#  push:
#    branches:
#      - main # Change this to the branch you want to trigger tests on
#  pull_request:
#    branches:
#      - main # Change this as needed
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: '8.0.x' # Specify the version of .NET you are using
#
#      - name: Cache NuGet packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.nuget/packages
#          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
#          restore-keys: |
#            ${{ runner.os }}-nuget-
#
#      - name: Restore dependencies
#        run: dotnet restore
#
#      - name: Build
#        run: dotnet build --configuration Release --no-restore
#
#  Unit-Test:
#    runs-on: ubuntu-latest
#    needs: build  # Ensures that the build job runs before this job
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: '8.0.x' # Specify the version of .NET you are using
#
#      - name: Cache NuGet packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.nuget/packages
#          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
#          restore-keys: |
#            ${{ runner.os }}-nuget-
#
#      # Instead of downloading artifacts, we build the test project again
#      - name: Build test project
#        run: dotnet build --configuration Release
#
#      - name: Run tests
#        run: dotnet test --configuration Release --verbosity normal
