name: .NET Tests

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger tests on
  pull_request:
    branches:
      - main # Change this as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Specify the version of .NET you are using

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish build artifacts
        run: dotnet publish -c Release -o ./publish
        # Upload build artifacts so they can be used in other jobs
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: ./publish

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the build job runs before this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Specify the version of .NET you are using

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: publish

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
